In [1]:
%load_ext autoreload
%autoreload 2

# Didactic example

This notebook contains the code for the didactic example.

In [2]:
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import LowerApproximation
from fuzzyroughrules.operators import ImplicatorInclusion
from pathlib import Path
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv(Path.cwd() / 'didactic-example.csv', sep=",")
data

,a_1,a_2,a_3,a_4,a_5,a_6,a_7,a_8,d
0,1,101,50,15,36,24.2,0.526,26,0
1,8,176,90,34,300,33.7,0.467,58,1
2,7,150,66,42,342,34.7,0.718,42,0
3,7,187,68,39,304,37.7,0.254,41,1
4,0,100,88,60,110,46.8,0.962,31,0
5,0,105,64,41,142,41.5,0.173,22,0
6,1,95,66,13,38,19.6,0.334,25,0


In [4]:
x = data[data.columns[:-1]].to_numpy()
y = data[data.columns[-1]].to_numpy()
x, y

(array([[1.00000, 101.00000, 50.00000, 15.00000, 36.00000, 24.20000,
         0.52600, 26.00000],
        [8.00000, 176.00000, 90.00000, 34.00000, 300.00000, 33.70000,
         0.46700, 58.00000],
        [7.00000, 150.00000, 66.00000, 42.00000, 342.00000, 34.70000,
         0.71800, 42.00000],
        [7.00000, 187.00000, 68.00000, 39.00000, 304.00000, 37.70000,
         0.25400, 41.00000],
        [0.00000, 100.00000, 88.00000, 60.00000, 110.00000, 46.80000,
         0.96200, 31.00000],
        [0.00000, 105.00000, 64.00000, 41.00000, 142.00000, 41.50000,
         0.17300, 22.00000],
        [1.00000, 95.00000, 66.00000, 13.00000, 38.00000, 19.60000,
         0.33400, 25.00000]]),
 array([0, 1, 0, 1, 0, 0, 0]))

In [5]:
scaler = MinMaxScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
x_scaled

array([[0.12500, 0.06522, 0.00000, 0.04255, 0.00000, 0.16912, 0.44740,
        0.11111],
       [1.00000, 0.88043, 1.00000, 0.44681, 0.86275, 0.51838, 0.37262,
        1.00000],
       [0.87500, 0.59783, 0.40000, 0.61702, 1.00000, 0.55515, 0.69075,
        0.55556],
       [0.87500, 1.00000, 0.45000, 0.55319, 0.87582, 0.66544, 0.10266,
        0.52778],
       [0.00000, 0.05435, 0.95000, 1.00000, 0.24183, 1.00000, 1.00000,
        0.25000],
       [0.00000, 0.10870, 0.35000, 0.59574, 0.34641, 0.80515, 0.00000,
        0.00000],
       [0.12500, 0.00000, 0.40000, 0.00000, 0.00654, 0.00000, 0.20406,
        0.08333]])

In [6]:
print(pd.DataFrame(x_scaled).to_latex(escape=False, float_format="%.2f"))

\begin{tabular}{lrrrrrrrr}
\toprule
{} &    0 &    1 &    2 &    3 &    4 &    5 &    6 &    7 \\
\midrule
0 & 0.12 & 0.07 & 0.00 & 0.04 & 0.00 & 0.17 & 0.45 & 0.11 \\
1 & 1.00 & 0.88 & 1.00 & 0.45 & 0.86 & 0.52 & 0.37 & 1.00 \\
2 & 0.88 & 0.60 & 0.40 & 0.62 & 1.00 & 0.56 & 0.69 & 0.56 \\
3 & 0.88 & 1.00 & 0.45 & 0.55 & 0.88 & 0.67 & 0.10 & 0.53 \\
4 & 0.00 & 0.05 & 0.95 & 1.00 & 0.24 & 1.00 & 1.00 & 0.25 \\
5 & 0.00 & 0.11 & 0.35 & 0.60 & 0.35 & 0.81 & 0.00 & 0.00 \\
6 & 0.12 & 0.00 & 0.40 & 0.00 & 0.01 & 0.00 & 0.20 & 0.08 \\
\bottomrule
\end{tabular}



/var/folders/_f/yf3dkr5x1397v4ntwhncxfhw0000gn/T/ipykernel_79618/1821567527.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(pd.DataFrame(x_scaled).to_latex(escape=False, float_format="%.2f"))


In [8]:
model = RuleGenerator(
    approximation=LowerApproximation(),
    inclusion_measure=ImplicatorInclusion(),
    with_reducts=True,
    optimise_slopes=False,
)

In [9]:
model.fit(x, y, _)

Set parameter Username
Academic license - for non-commercial use only - expires 2025-10-30


RuleGenerator(with_reducts=True, apply_relabelling=False, relabelling_threshold=0.0, discard_uncertain_objects=False, add_uncovered_objects=True, certainty_threshold=0.0, print_nr_of_rule_candidates=False, print_changes=False, optimise_attribute_order=False, optimise_slopes=False, slope_options=None, covering_threshold=1e-06, inclusion_threshold=0.999999, priors_influence=0, use_gran_approx=False, approximation=<fuzzyroughrules.approximations.LowerApproximation object at 0x31ce05630>, inclusion_measure=<fuzzyroughrules.operators.ImplicatorInclusion object at 0x31ceffbe0>, attribute_ordering=None)

In [11]:
model.rules_

[Rule(antecedent=array([1.00000, 0.88043, 1.00000, 0.44681, 0.86275, 0.51838, 0.37262,
        1.00000]), reducts=array([<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>],
       dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
        1.00000]), credibility=0.5999999999999999, decision=1, as_string='Not yet extracted'),
 Rule(antecedent=array([0.00000, 0.05435, 0.95000, 1.00000, 0.24183, 1.00000, 1.00000,
        0.25000]), reducts=array([<RelationTypes.DOMINANT: -1>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.000

In [13]:
model.reducts_

array([[<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <Relatio

In [32]:
from fuzzyroughrules.full_inclusion_frri import GranularRuleGenerator
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import MulticlassMSECVXApproximation
from fuzzyroughrules.operators import StrictFuzzyInclusion
from pathlib import Path

gran_model = GranularRuleGenerator(
    approximation=MulticlassMSECVXApproximation(),
    inclusion_measure=StrictFuzzyInclusion(),
    apply_relabelling=True,
    covering_threshold=.50 - 1e-6,
)

In [33]:
from hhelper.data_loader import get_dataset

x, y = get_dataset(Path.cwd() / 'keel-data' / 'ecoli-10-fold', '1tra')
x_test, y_test = get_dataset(Path.cwd() / 'keel-data' / 'ecoli-10-fold', '1tst')

In [37]:
gran_model.fit(x, y, _)

1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 2

GranularRuleGenerator(with_reducts=True, apply_relabelling=True, relabelling_threshold=0.0, discard_uncertain_objects=False, add_uncovered_objects=True, certainty_threshold=0.0, print_nr_of_rule_candidates=False, print_changes=False, optimise_attribute_order=False, optimise_slopes=False, slope_options=None, covering_threshold=0.499999, inclusion_threshold=0.999999, priors_influence=0, use_gran_approx=False, approximation=MulticlassMSECVXApproximation(weights=None, nn_approx=-1, n_jobs=None), inclusion_measure=<fuzzyroughrules.operators.StrictFuzzyInclusion object at 0x31d230340>, attribute_ordering=None)

In [38]:
gran_model.predict(x_test)

array([' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp',
       ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' im', ' cp', ' im',
       ' im', ' im', ' im', ' im', ' im', ' im', ' im', ' im', ' pp',
       ' cp', ' omL', ' cp', ' cp', ' pp', ' pp', ' pp'], dtype=object)

In [39]:
model2.get_rules_as_string()

["[{'attribute': 2, 'type': 'l', 'bounds': [66.0]}, {'attribute': 7, 'type': 'l', 'bounds': [36.4]}], class: 1",
 "[{'attribute': 0, 'type': 'r', 'bounds': [7.565217391304348]}, {'attribute': 1, 'type': 'r', 'bounds': [187.0]}], class: 0"]

In [23]:
model2.selected_indexes

array([1, 4])

In [37]:
from fuzzyroughrules.approximations import LowerApproximation

appr = LowerApproximation()
pos_reg = appr.get_approximation(x_scaled, y)

In [38]:
pos_reg

array([0.93478, 0.60000, 0.58809, 0.58809, 0.94565, 0.89130, 0.91667])

Stap per stap berekening van appr.get_approximation(x_scaled, y)

In [42]:
from fuzzyroughrules.fuzzy_operators import triangular_similarity, discernibility_matrix, get_ind_low_apr, lukasiewicz_implicator

rel_mat = triangular_similarity(x_scaled, x_scaled)

In [43]:
rel_mat

array([[1.00000, 0.00000, 0.00000, 0.06522, 0.04255, 0.36397, 0.60000],
       [0.00000, 1.00000, 0.40000, 0.45000, 0.00000, 0.00000, 0.08333],
       [0.00000, 0.40000, 1.00000, 0.41191, 0.12500, 0.12500, 0.00654],
       [0.06522, 0.45000, 0.41191, 1.00000, 0.05435, 0.10870, 0.00000],
       [0.04255, 0.00000, 0.12500, 0.05435, 1.00000, 0.00000, 0.00000],
       [0.36397, 0.00000, 0.12500, 0.10870, 0.00000, 1.00000, 0.19485],
       [0.60000, 0.08333, 0.00654, 0.00000, 0.00000, 0.19485, 1.00000]])

In [44]:
fuzzy_set = discernibility_matrix(y, y)

In [45]:
fuzzy_set

array([[1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1]])

In [47]:
impl = lukasiewicz_implicator(rel_mat, fuzzy_set)
impl

array([[1.00000, 1.00000, 1.00000, 0.93478, 1.00000, 1.00000, 1.00000],
       [1.00000, 1.00000, 0.60000, 1.00000, 1.00000, 1.00000, 0.91667],
       [1.00000, 0.60000, 1.00000, 0.58809, 1.00000, 1.00000, 1.00000],
       [0.93478, 1.00000, 0.58809, 1.00000, 0.94565, 0.89130, 1.00000],
       [1.00000, 1.00000, 1.00000, 0.94565, 1.00000, 1.00000, 1.00000],
       [1.00000, 1.00000, 1.00000, 0.89130, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.91667, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000]])

In [51]:
np.min(impl, 0)

array([0.93478, 0.60000, 0.58809, 0.58809, 0.94565, 0.89130, 0.91667])

Voor sectie 3.3 Rule selection

In [82]:
from fuzzyroughrules.fuzzy_operators import lukasiewicz_t_norm
from fuzzyroughrules.operators import triangular_relation

covering = np.zeros((model.n_samples, model.n_samples))
for i in range(model.n_samples):
    current_covering = lukasiewicz_t_norm(
        # fo.general_triangular_relation(self.X_scaled, self.X_scaled[i], self.theta, self.reducts[i]),
        triangular_relation(
            model.X_scaled,
            model.X_scaled[i],
            model.slopes[i],
            model.reducts[i]
        ),
        model.positive_region[i]
    )
    if len(current_covering.shape) > 1:
        current_covering = current_covering.T
    covering[i, :] = (1 * (current_covering > model.covering_threshold))

In [83]:
model.covering_threshold

1e-06

In [84]:
covering

array([[1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 1.00000, 1.00000],
       [0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 1.00000],
       [0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000]])

In [81]:
from fuzzyroughrules.operators import RelationTypes

lukasiewicz_t_norm(
    triangular_relation(
        x_scaled[3],
        x_scaled[0], 
        slopes=np.ones(model.n_attributes, dtype=float),
        rel_types=np.array([RelationTypes.UNUSED, RelationTypes.DOMINANT, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE])
    ),
    model.positive_region[0]
)


array([0.00000])

In [80]:
model.reducts

array([[<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <Relatio

In [74]:
model.positive_region[0]

0.9347826086956521

In [58]:
model.inclusion_threshold

0.9999

In [62]:
model2.reducts

array([[ 0, -1, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0, -1,  0],
       [ 0,  0, -1,  0,  0,  0,  1,  0],
       [ 0,  1,  0,  0,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  0,  0, -1]])