# Testing if QuickRules works correctly

In [29]:
import numpy
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
indices = [2, 0, 4]

selected = arr[indices]
print(selected)


[30 10 50]


In [31]:
from hhelper.data_loader import get_dataset
from pathlib import Path
import numpy as np
from sklearn.metrics import balanced_accuracy_score, accuracy_score
from numpy import genfromtxt

In [32]:
data_sets = [
    # 'australian',
    # 'cleveland',
    # 'glass',
    # 'heart',
    # 'ionosphere',
    # 'pima',
    # 'wine',
    # 'bupa',
    # 'saheart',
    'wisconsin',
    # 'crx',
    'ecoli',
    # 'haberman',
    # 'mammographic'
             ]

In [33]:
data_path = Path.cwd() / 'keel-data'
results_path = Path.cwd() / 'trun-lin-owa-qr-combo-minmax-results'
metric = accuracy_score

scores = calculate_score(
    data_folder=data_path,
    results_folder=results_path,
    include=data_sets,
    metric=metric
)

NameError: name 'calculate_score' is not defined

In [34]:
scores

NameError: name 'scores' is not defined

In [35]:
for d in data_sets:
    total = 0
    for fold in range (1, 11):
        _, y_test = get_dataset(Path.cwd() / 'keel-data' / f'{d}-10-fold', f'{fold}tst')
        numpy_pred = genfromtxt(
            Path.cwd() / 'close-min-max-combo-results' / f'{d}' / f'fold{fold}' / f'fold{fold}.dat',
            comments='@',
            missing_values='None',  # temp do not include!!!!!
            filling_values='0',
            # dtype='str'
        )
        total += accuracy_score(y_test, numpy_pred)
        # print(accuracy_score(y_test, numpy_pred))
    print(f'{d} average: {total/10}')

FileNotFoundError: /Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/close-min-max-combo-results/wisconsin/fold1/fold1.dat not found.

Let's check the example from the paper.

In [3]:
example_x = np.array(
    [[1, 101, 50, 15, 36, 24.2, 0.526, 26],
     [8, 176, 90, 34, 300, 33.7, 0.467, 58],
     [7, 150, 66, 42, 342, 34.7, 0.718, 42],
     [7, 187, 68, 39, 304, 37.7, 0.254, 41],
     [0, 100, 88, 60, 110, 46.8, 0.962, 31],
     [0, 105, 64, 41, 142, 41.5, 0.173, 22],
     [1, 95, 66, 13, 38, 19.6, 0.334, 25]])

example_y = np.array([0, 1, 0, 1, 0, 0, 0])

In [11]:
from quickrules.fuzzy_operators import MinTNorm, KleeneDienesImplicator
from quickrules.quickrules import QuickRules
from quickrules.relations import RelationFactory, StatisticalRelation
from quickrules.owaquickrules import OWAQuickRules
from quickrules.weights import LinearWeights, ExponentialWeights

minmax_factory = RelationFactory(StatisticalRelation, MinTNorm())
model = OWAQuickRules(MinTNorm(), KleeneDienesImplicator(), minmax_factory, ExponentialWeights())

In [12]:
model.fit(example_x, example_y)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.994430588216555
0.9809871606850785
0.9921259842519685
1.0
1.0
1.0
1.0
0.9977264816141256
0.9977264816141256
1.0
1.0
1.0
1.0
1.0
0.9933310575929631
0.9933310575929631
0.9581376965147205
0.9933310575929631
0.9945361309339578
0.9933310575929631
1.0
0.9883163113984453
0.9862400751127862
0.9805304253272237
1.0
0.9846828978985418
1.0
1.0
0.9948490829356652
0.984287906075215
0.9945897402038846
1.0
1.0
1.0
1.0
0.9912908301375104
0.9826665155071848
0.9859006334935568
1.0
0.993806255238022
1.0
0.9939439518364169
0.9858323799287272
0.9998600497383506
0.9838347011531346
1.0
0.9946218380543468
0.9870392541833487
1.0
1.0
0.9927914600430934
0.9903529443695267
0.9987807421632167
1.0
1.0
1.0
0.9977264816141256
0.9977264816141256
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9977264816141256
0.9977264816141256
1.0
1.0
1.0
1.0
1.0
0.9977264816141256
0.9977264816141256
1.0
1.0
1.0
1.0
1.0
0.9977264816141256
0.9977264816141256
1.0
1.0
1.0
1.0
1.0
0.9998600497383506
0.9

In [9]:
x_train, y_train = get_dataset(Path.cwd() / 'keel-data' / 'cleveland-10-fold', '1tra')

In [15]:
model.fit(x_train, y_train)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [18]:
x_test, y_test = get_dataset(Path.cwd() / 'keel-data' / 'cleveland-10-fold', '1tst')

In [17]:
preds = model.predict(x_test)

In [18]:
accuracy_score(y_true=y_test, y_pred=preds)

0.5666666666666667

reverse = False: 0.5666...

Playing with weigths
-------

In [38]:
from quickrules.weights import ExponentialWeights

In [20]:
weights = LinearWeights()
weights(336)

array([5.93471810e-03, 5.91705525e-03, 5.89939240e-03, 5.88172955e-03,
       5.86406669e-03, 5.84640384e-03, 5.82874099e-03, 5.81107814e-03,
       5.79341529e-03, 5.77575244e-03, 5.75808959e-03, 5.74042673e-03,
       5.72276388e-03, 5.70510103e-03, 5.68743818e-03, 5.66977533e-03,
       5.65211248e-03, 5.63444963e-03, 5.61678677e-03, 5.59912392e-03,
       5.58146107e-03, 5.56379822e-03, 5.54613537e-03, 5.52847252e-03,
       5.51080967e-03, 5.49314681e-03, 5.47548396e-03, 5.45782111e-03,
       5.44015826e-03, 5.42249541e-03, 5.40483256e-03, 5.38716970e-03,
       5.36950685e-03, 5.35184400e-03, 5.33418115e-03, 5.31651830e-03,
       5.29885545e-03, 5.28119260e-03, 5.26352974e-03, 5.24586689e-03,
       5.22820404e-03, 5.21054119e-03, 5.19287834e-03, 5.17521549e-03,
       5.15755264e-03, 5.13988978e-03, 5.12222693e-03, 5.10456408e-03,
       5.08690123e-03, 5.06923838e-03, 5.05157553e-03, 5.03391267e-03,
       5.01624982e-03, 4.99858697e-03, 4.98092412e-03, 4.96326127e-03,
      

-> weights are descending

In [12]:
for x, y in zip(list(range(10)), list(range(2))):
    print(x, y)

0 0
1 1


In [1]:
import numpy as np

arrowCell = {'up': False, 'left': False, 'right': False}
brrowCell = {'up': True, 'left': False, 'right': False}

np.array([arrowCell, brrowCell])

array([{'up': False, 'left': False, 'right': False},
       {'up': True, 'left': False, 'right': False}], dtype=object)

In [36]:
# from fuzzyroughrules.approximations import LowerApproximation
# from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.non_overlap_rules import RuleGenerator
from quickrules.data_handling import get_dataset
from pathlib import Path
import numpy as np

ModuleNotFoundError: No module named 'quickrules.data_handling'

In [9]:
x_train, y_train = get_dataset(Path.cwd() / 'keel-data' / 'cleveland-10-fold', '2tra')
x_test, y_test = get_dataset(Path.cwd() / 'keel-data' / 'cleveland-10-fold', '2tst')

classes = list(np.unique(np.append(y_train, y_test)))
y_train = np.array([classes.index(label) for label in y_train])
y_test = np.array([classes.index(label) for label in y_test])

In [10]:
model = RuleGenerator() # LowerApproximation())
model.fit(x_train, y_train, 0)

34


In [19]:
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import LowerApproximation

l = LowerApproximation()
print(l)
print(f"{l}")
print(repr(l))
print(str(l))
r = RuleGenerator(l)
print(r)

LowerApproximation
LowerApproximation
LowerApproximation
@non-overlap-rules-base
@approximation: LowerApproximation
@scaler: MinMaxScaler()


In [10]:
x_train

array([[63.,  1.,  1., ...,  3.,  0.,  6.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  7.],
       ...,
       [68.,  1.,  4., ...,  2.,  2.,  7.],
       [57.,  1.,  4., ...,  2.,  1.,  7.],
       [57.,  0.,  2., ...,  2.,  1.,  3.]])

In [11]:
from fuzzyroughrules.filter_frri import Filter, FilterRuleGenerator

In [12]:
f = Filter()

In [13]:
f.fit(x_train, y_train)

Filter(metric=<function mutual_info_classif at 0x3031d4160>, attribute_ratio=1)

In [14]:
f.ordered_features_

array([11, 12,  9,  2,  8,  7, 10,  1,  0,  4,  6,  5,  3])

In [16]:
x_train[:, f.ordered_features_]

array([[0.00000, 6.00000, 2.30000, ..., 2.00000, 1.00000, 145.00000],
       [3.00000, 3.00000, 1.50000, ..., 2.00000, 0.00000, 160.00000],
       [2.00000, 7.00000, 2.60000, ..., 2.00000, 0.00000, 120.00000],
       ...,
       [2.00000, 7.00000, 3.40000, ..., 0.00000, 1.00000, 144.00000],
       [1.00000, 7.00000, 1.20000, ..., 0.00000, 0.00000, 130.00000],
       [1.00000, 3.00000, 0.00000, ..., 2.00000, 0.00000, 130.00000]])

In [17]:
f.attribute_ratio = 0.8

In [28]:
f.transform(x_test)

array([[0.00000, 6.00000, 0.40000, 4.00000, 0.00000, 148.00000, 2.00000,
        1.00000, 57.00000, 192.00000],
       [1.00000, 6.00000, 0.60000, 3.00000, 1.00000, 142.00000, 2.00000,
        1.00000, 56.00000, 256.00000],
       [0.00000, 3.00000, 1.20000, 4.00000, 0.00000, 160.00000, 1.00000,
        1.00000, 54.00000, 239.00000],
       [0.00000, 3.00000, 0.60000, 2.00000, 0.00000, 171.00000, 1.00000,
        1.00000, 49.00000, 266.00000],
       [0.00000, 3.00000, 1.80000, 1.00000, 1.00000, 144.00000, 2.00000,
        1.00000, 64.00000, 211.00000],
       [0.00000, 3.00000, 1.60000, 3.00000, 0.00000, 158.00000, 2.00000,
        0.00000, 50.00000, 219.00000],
       [0.00000, 7.00000, 1.20000, 4.00000, 1.00000, 142.00000, 2.00000,
        0.00000, 51.00000, 305.00000],
       [2.00000, 7.00000, 1.80000, 4.00000, 1.00000, 99.00000, 2.00000,
        1.00000, 62.00000, 267.00000],
       [2.00000, 6.00000, 0.60000, 4.00000, 0.00000, 158.00000, 1.00000,
        1.00000, 65.00000, 248.0

In [21]:
np.rint(x_test.shape[1]*f.attribute_ratio)

10.0

In [27]:
x_test[:, :int(np.rint(x_test.shape[1]*f.attribute_ratio))]

array([[57.00000, 1.00000, 4.00000, 140.00000, 192.00000, 0.00000,
        0.00000, 148.00000, 0.00000, 0.40000],
       [56.00000, 1.00000, 3.00000, 130.00000, 256.00000, 1.00000,
        2.00000, 142.00000, 1.00000, 0.60000],
       [54.00000, 1.00000, 4.00000, 140.00000, 239.00000, 0.00000,
        0.00000, 160.00000, 0.00000, 1.20000],
       [49.00000, 1.00000, 2.00000, 130.00000, 266.00000, 0.00000,
        0.00000, 171.00000, 0.00000, 0.60000],
       [64.00000, 1.00000, 1.00000, 110.00000, 211.00000, 0.00000,
        2.00000, 144.00000, 1.00000, 1.80000],
       [50.00000, 0.00000, 3.00000, 120.00000, 219.00000, 0.00000,
        0.00000, 158.00000, 0.00000, 1.60000],
       [51.00000, 0.00000, 4.00000, 130.00000, 305.00000, 0.00000,
        0.00000, 142.00000, 1.00000, 1.20000],
       [62.00000, 1.00000, 4.00000, 120.00000, 267.00000, 0.00000,
        0.00000, 99.00000, 1.00000, 1.80000],
       [65.00000, 1.00000, 4.00000, 110.00000, 248.00000, 0.00000,
        2.00000, 158.0

In [5]:
import numpy as np
from fuzzyroughrules.rule_induction_base import RelationTypes, Rule
from numpy import array

unused = RelationTypes.UNUSED

In [6]:
unused

RelationTypes.UNUSED

In [7]:
r = Rule(antecedent=array([0.25843, 0.35632, 1.00000, 1.00000, 0.62500, 0.26374, 0.35354]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
       RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
       RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.101123595505618, decision=0)

In [9]:
r2 = Rule(antecedent=array([0.32584, 0.41379, 1.00000, 1.00000, 0.54545, 0.47253, 0.52525]), reducts=array([RelationTypes.DOMINANT, RelationTypes.DOMINANT,
       RelationTypes.UNUSED, RelationTypes.UNUSED,
       RelationTypes.DOMINATED, RelationTypes.INDISCERNIBLE,
       RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.17045454545454541, decision=0)

In [10]:
l = [r, r2]

In [11]:
np.sum(np.array([rule.reducts for rule in l]) != RelationTypes.UNUSED) / len(l)

3.5