## Diving into the details of the owa implementations.

In [28]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[autoreload of fuzzyroughrules.rule_induction_base failed: Traceback (most recent call last):
  File "/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 261, in check
    superreload(m, reload, self.old_objects)
  File "/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 459, in superreload
    module = reload(module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thes

In [29]:
import numpy as np
from quickrules.data_handling import get_dataset, test_save
from pathlib import Path
import fuzzyroughrules.fuzzy_operators as fo
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import LowerApproximation, MulticlassMSECVXApproximation, OWALowerApproximation
from fuzzyroughrules.operators import ImplicatorInclusion, OWAImplicatorInclusion
from quickrules.data_handling import test_save
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score

In [30]:
for nr in range(1, 11):
    name = 'pima' # 'bupa
    # nr = 7
    x_train, y_train, t_train = get_dataset(
        Path.cwd() / 'keel-data' / f'{name}-10-fold',
        f"{nr}tra",
        get_datatypes=True
    )
    x_test, y_test = get_dataset(
        Path.cwd() / 'keel-data' / f'{name}-10-fold',
        f"{nr}tst"
    )
    classes = list(np.unique(np.append(y_train, y_test)))
    y_train = np.array([classes.index(label) for label in y_train])
    y_test = np.array([classes.index(label) for label in y_test])
    model = RuleGenerator(
        OWAImplicatorInclusion()
    )
    model.fit(x_train, y_train, _)
    print(balanced_accuracy_score(y_test, model.predict(x_test)))

0.6562962962962963
0.7057142857142857
0.6407692307692308
0.7162962962962962
0.7062962962962962
0.7353846153846153
0.7803703703703704
0.62
0.6107407407407407
0.5837037037037037



Comparing this to acc when using a higher threshold

In [25]:
name = 'ecoli' # 'bupa
nr = 1
x_train, y_train, t_train = get_dataset(
    Path.cwd() / 'keel-data' / f'{name}-10-fold',
    f"{nr}tra",
    get_datatypes=True
)
x_test, y_test = get_dataset(
    Path.cwd() / 'keel-data' / f'{name}-10-fold',
    f"{nr}tst"
)
classes = list(np.unique(np.append(y_train, y_test)))
y_train = np.array([classes.index(label) for label in y_train])
y_test = np.array([classes.index(label) for label in y_test])
model = RuleGenerator(
    approximation=OWALowerApproximation()
)
model.fit(x_train, y_train, _)
print(balanced_accuracy_score(y_test, model.predict(x_test)))

0.14285714285714285


In [26]:
print(model.predict(x_test))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
len(model.get_rules_as_string())

14

In [73]:
name = 'ecoli' # 'bupa
# nr = 7
x_train, y_train, t_train = get_dataset(
    Path.cwd() / 'keel-data' / f'{name}-10-fold',
    f"{nr}tra",
    get_datatypes=True
)

In [74]:
_, _, counts = np.unique(y_train, return_inverse=True, return_counts=True)

In [75]:
priors = np.divide(counts, max(counts))

In [76]:
priors

array([1.00000, 0.53488, 0.01550, 0.01550, 0.24806, 0.13953, 0.03101,
       0.36434])

In [77]:
(priors * 0.05 + 0.95) * (1-1e-6)

array([1.00000, 0.97674, 0.95077, 0.95077, 0.96240, 0.95698, 0.95155,
       0.96822])

In [81]:
if 0:
    print ( True)